import { cookies, headers } from "next/headers";

export type Lang = "es" | "en" | "pt";
export const LANGS: Lang[] = ["es", "en", "pt"];
export const LANG_LABEL: Record<Lang, string> = { es: "ES", en: "EN", pt: "PT" };

const es = {
  nav: { hoy: "Hoy", entrenar: "Entrenar", comidas: "Comidas", mente: "Mente", progreso: "Progreso", menus: "Menús", chat: "Chat", soporte: "Soporte", planes: "Planes", perfil: "Perfil", micoach: "Mi coach", salir: "Salir", panelCoach: "Panel coach", admin: "Admin" },
  common: { gratis: "Gratis", premium: "Premium", desde: "Desde", desdePlan: "Disponible desde el plan", desbloquear: "Desbloquear", verPlanes: "Ver planes", guardar: "Guardar", enviar: "Enviar", agregar: "Agregar", empezarGratis: "Empezar gratis", crearCuenta: "Crear cuenta", iniciarSesion: "Iniciar sesión", entrar: "Entrar", volver: "← Volver", min: "min", ejercicios: "ejercicios", mes: "/mes", disclaimer: "Contenido educativo. Cada persona lo practica bajo su propia responsabilidad; consulta a un profesional de salud.", issa: "Coach certificada ISSA · CPT · Nutrición · Fuerza y acondicionamiento", tagline: "Pequeños hábitos, grandes resultados" },
  home: { pill: "Gimnasio · Nutrición · Paz mental", h1a: "Energía para moverte.", h1b: "Calma para quedarte.", text: "Entrena con cronómetro y guía en video, registra tus comidas, y cuida tu mente con reflexión y worship. Con Maleja, coach certificada ISSA, en tu idioma.", go: "GO · Empezar gratis", miembros: "miembros", anos: "años", transf: "transformaciones", energia: "Energía", entrenar: "Entrenar", entrenarText: "Funcional, calistenia, HIIT. Cronómetro por intervalos, series y descansos guiados, demo en video.", verRutinas: "Ver rutinas", balance: "Balance", comerBien: "Comer bien y estar en paz", comerBienText: "Menús por objetivo, registro de comidas, pilates, yoga, reflexión diaria y worship.", explorar: "Explorar", tuCoach: "Tu coach", coachBio: "Coach certificada ISSA (CPT, Nutrition Coach, Strength & Conditioning). Cambió su vida con hábitos pequeños; hoy acompaña a cientos de mujeres en tres idiomas. Chat 1:1 y plan a tu medida desde el plan Pro.", planes: "Planes", planesSub: "Empieza gratis. Sube cuando quieras más.", free: ["2 rutinas con cronómetro", "1 menú con recetas", "Reflexión + worship", "Registro de comidas", "Asistente IA (5/día)", "Soporte"], crearGratis: "Crear cuenta gratis", elegir: "Elegir", masElegido: "Más elegido", footer: "Contenido educativo. Cada persona lo practica bajo su propia responsabilidad; consulta a un profesional de salud antes de iniciar un programa." },
  auth: { email: "Email", password: "Contraseña", name: "Tu nombre", namePh: "Como quieres que te llame la app", goal: "Tu objetivo", coachQ: "¿Eres coach? Ingresa tu código", coachCode: "Código de coach", coachHint: "Solo para coaches invitadas por Small Habits. Los miembros lo dejan vacío.", entrar: "Entrar", crear: "Crear mi cuenta", wait: "Un momento…", haveAccount: "¿Ya tienes cuenta?", firstTime: "¿Primera vez?", crearGratis: "Crea tu cuenta gratis", signupPill: "Crea tu cuenta gratis", signupSub: "Sin tarjeta. Lo gratis se queda gratis: 2 rutinas, 1 menú, reflexión diaria y tu registro de comidas.", signupFine: "Al crear tu cuenta aceptas que el contenido es educativo y lo practicas bajo tu responsabilidad.", hub: "Hub wellness · by Maleja", quote: "Wellness from the inside out." },
  goals: { Tonificar: "Tonificar", "Perder peso": "Perder peso", "Ganar fuerza": "Ganar fuerza", Resistencia: "Resistencia", Flexibilidad: "Flexibilidad", "Salud integral": "Salud integral" },
  dash: { hola: "Hola", objetivo: "objetivo", quote: "Un pequeño hábito hoy. Uno más mañana.", hoyToca: "Hoy toca", asignadoPor: "Asignado por", empiezaSuave: "Empieza suave. Lo importante es empezar.", calorias: "Calorías", de: "de", peso: "Peso", kg: "kg", addProfile: "añádelo en tu perfil", entrenos: "Entrenos", estaSemana: "esta semana", diasActivos: "Días activos", ult30: "últimos 30 días", nutricion: "Nutrición", sinComidas: "Aún no registras comidas hoy", quedan: "Te quedan {n} kcal", registrar: "Registrar comida", verMenu: "Ver menú", pazMental: "Paz mental", reflexionHoy: "Reflexión de hoy · 5 min", quoteMente: "Respira. Agradece por tu cuerpo, que hoy se movió.", unread: "Tienes {n} mensaje(s) sin leer.", welcome: "Bienvenida, {n}. Cuéntame cómo te sientes hoy y armamos tu semana.", eligeCoach: "Elige tu coach", nuevo: "{n} nuevo(s)" },
  routines: { title: "Entrenar", kicker: "2 rutinas gratis · el resto desde Básico", demo: "Demo avatar", ejercicios: "Ejercicios", series: "Series", reps: "Reps", descanso: "Descanso", musculos: "Músculos", warn: "Realiza los ejercicios bajo tu responsabilidad. Detente ante cualquier dolor.", trabajo: "Trabajo", descansoT: "Descanso", pausa: "Pausa", reiniciar: "Reiniciar", completada: "Sesión completada", completadaText: "La energía descansa. Registra cómo te sentiste en Progreso.", repetir: "Repetir" },
  nutrition: { title: "Menús y recetas", kicker: "1 menú gratis · el resto desde Básico", avatar: "Avatar explica", planDia: "Plan del día", recetas: "Recetas", marcas: "Marcas recomendadas por limpieza:", marcasText: "avena sin azúcar añadida, proteína sin edulcorantes artificiales, aceite de oliva extra virgen, huevos de pastoreo. Lee siempre la etiqueta.", menu: "Menú", kcalDia: "kcal/día" },
  mind: { title: "Paz mental", kicker: "Reflexión y worship gratis · meditación y journal desde Básico", avatar: "Avatar guía", completar: "Completar sesión", guardar: "Guardar", respiracion: "Respiración 4-7-8", banner: "Respira. Hoy también cuenta.", journalPh: "Escribe aquí...", inhala: "Inhala", sosten: "Sostén", exhala: "Exhala" },
  food: { title: "Comidas", kicker: "Registro manual gratis · foto con IA desde Básico", fotoIA: "Foto → IA", tocaFoto: "Toca para tomar foto de tu plato", desdeBasico: "Desde el plan Básico", probar: "Probar con foto de ejemplo", analizando: "Analizando tu comida…", manual: "Registro manual", quecomiste: "¿Qué comiste?", calorias: "Calorías aprox.", guardando: "Guardando…", hoy: "Hoy", proteina: "Proteína", carbos: "Carbos", grasas: "Grasas", sinComidas: "Todavía no hay comidas hoy. Registra la primera arriba.", hist30: "Historial de 30 días", ult30: "Últimos 30 días", histText: "Promedio, proteína y tendencia semanal aparecen aquí a partir de tu segundo día de registro.", err: "No se pudo guardar. Revisa tu conexión e inténtalo de nuevo." },
  progress: { title: "Progreso", kicker: "8 semanas contigo", banner: "Cada día suma.", racha: "Racha", peso: "Peso", entrenos: "Entrenos", totales: "totales", dias: "días · mejor 19", pesoSem: "Peso · 8 semanas", kcalSem: "Calorías · esta semana", kcalFeature: "Calorías semanales", reloj: "Reloj conectado", relojFeature: "Apple Watch y Garmin", sync: "sincronizado", pasos: "Pasos", bpm: "BPM reposo", kcalAct: "Kcal activas", sueno: "Sueño", via: "Vía Apple HealthKit y Garmin Connect API. Sincroniza cada 15 minutos." },
  chat: { title: "Chat", kicker: "Asistente IA gratis · tu coach desde Pro", ia: "Asistente IA", ilimitado: "Ilimitado", porDia: "5 / día", iaFine: "Información general y educativa. No sustituye consejo médico.", feature: "Chat directo con", coachFine: "Tu coach responde normalmente en menos de 24 h. Los mensajes quedan guardados.", limite: "Límite diario — sube de plan para ilimitado", placeholder: "Escribe tu pregunta…", writeTo: "Escribe a", desdePro: "Disponible desde el plan Pro", noCoach: "Todavía no hay una coach en la plataforma. En cuanto entre, tu mensaje le llega.", firstMsg: "Escribe el primer mensaje a", msgsHoy: "mensajes hoy", hello: "Hola {n}. Soy tu asistente. ¿Qué necesitas hoy: calorías, rutina, menú o un momento de paz?" },
  upgrade: { title: "Planes", kicker: "Lo gratis se queda gratis. El pago se activa solo cuando Stripe lo confirma.", masElegido: "Más elegido", elite: "Transformación guiada", tuPlan: "Tu plan", suscribir: "Suscribirme con Stripe", pendiente: "Link de pago pendiente", demo: "Modo demostración", demoText: "Cambia el plan sin pagar para mostrar cómo se ve la app en cada nivel. En producción se desactiva.", verComo: "Ver como" },
  coaches: { title: "Elige tu coach", kicker: "Puedes cambiar cuando quieras · tu historial se conserva", intro: "Cada coach tiene su estilo. Elige a la persona que te inspire confianza: será quien te asigne rutina y menú y con quien hables en el chat.", tuCoach: "Tu coach", noBio: "Esta coach aún no escribió su presentación.", miembros: "miembro(s)", elegirA: "Elegir a", none: "Todavía no hay coaches registradas.", defaultSpec: "Coach Small Habits" },
  profile: { title: "Mi perfil", cuenta: "Cuenta creada", plan: "plan", nombre: "Nombre", objetivo: "Objetivo", pesoKg: "Peso (kg)", alturaCm: "Altura (cm)", note: "Cada vez que guardas un peso nuevo se añade a tu historial de progreso.", guardar: "Guardar cambios", guardando: "Guardando…", cerrar: "Cerrar sesión" },
  tickets: { title: "Soporte", kicker: "Gratis para todos · prioridad en Elite", nuevo: "Nuevo ticket", prio: "Prioritario · 24h", asunto: "Asunto", cuenta: "Cuéntanos qué pasa…", enviar: "Enviar ticket", mis: "Mis tickets", cats: ["Entrenamiento", "Nutrición", "Pagos", "Técnico", "Otro"] },
  wearables: { title: "Mi reloj", kicker: "Sincroniza pasos, sueño y entrenos · desde Pro", feature: "Conectar tu reloj", connected: "Conectado", notConnected: "Sin conectar", connectGoogle: "Conectar con Google Health", googleText: "Fitbit, Pixel Watch y relojes Android (Wear OS, Samsung) a través de la app Google Health.", garminText: "Solicitud de acceso enviada a Garmin. Se activa al recibir la aprobación.", appleText: "Apple solo permite leer datos del Apple Watch desde una app instalada en el iPhone. Llega con la versión para App Store.", soon: "Próximamente", lastSync: "Última sincronización", syncNow: "Sincronizar ahora", disconnect: "Desconectar", connectedMsg: "Reloj conectado. Tus datos empiezan a aparecer aquí y en Progreso.", noDataYet: "Aún no hay datos: usa el reloj unas horas y vuelve a sincronizar.", errorMsg: "No se pudo conectar. Inténtalo de nuevo.", todayData: "Hoy", history: "Últimos 14 días", day: "Día", privacy: "Solo se guardan resúmenes diarios (pasos, ritmo cardíaco en reposo, calorías activas, sueño, entrenos). Puedes desconectar cuando quieras y se borran." },
  plans: {
    basico: { tagline: "Entrena y come bien", features: ["Todas las rutinas (funcional, calistenia, pilates, yoga, estiramientos)", "Todos los menús y recetas", "Registro de comidas con foto (10/día)", "Meditaciones y worship completos", "Progreso completo con gráficos"] },
    pro: { tagline: "Con tu coach", features: ["Todo lo de Básico", "Chat 1:1 con tu coach", "Asistente IA ilimitado", "Registro de comidas ilimitado", "Plan de la semana asignado por tu coach"] },
    elite: { tagline: "Transformación guiada", features: ["Todo lo de Pro", "Plan de entrenamiento y nutrición hecho por tu coach para ti", "Videollamada mensual 1:1", "Chat 1:1 ilimitado", "Soporte prioritario"] },
  },
  content: {
    routines: { routine_1: ["Calistenia para principiantes", "Rutina básica de movimientos con peso corporal. Perfecto para iniciarse."], routine_2: ["Funcional HIIT 20 min", "Alta intensidad por intervalos. Quema máxima en poco tiempo."], routine_3: ["Pilates para flexibilidad", "Sesión suave enfocada en elongación y control."], routine_4: ["Yoga Vinyasa Flow", "Secuencia continua de posturas vinculadas con respiración."], routine_5: ["Estiramientos post-entreno", "Elongación para recuperación después de entrenar."] },
    menus: { menu_1: "Tonificación", menu_2: "Pérdida de grasa", menu_3: "Ganancia muscular", menu_4: "Vegetariano balance" },
    sessions: { m_1: ["Reflexión", "Pequeños hábitos, grandes cambios", "¿Qué hábito pequeño cumpliste hoy? Anótalo. No importa el tamaño: importa la repetición. Mañana, repítelo una vez más."], m_2: ["Worship", "Gratitud y propósito", "Respira. Agradece por tu cuerpo, que hoy se movió. Agradece por tu mente, que hoy eligió cuidarse. Pide fuerza para mañana."], m_3: ["Meditación", "Antes de entrenar: enfoque", "Cierra los ojos. Visualiza tu sesión completa. Cada repetición con intención. Tú eres capaz."], m_4: ["Meditación", "Recuperación post-entreno", "Tu cuerpo trabajó. Respira lento. Siente cómo el cansancio se vuelve satisfacción. Descansa."], m_5: ["Journal", "Diario de la noche", "Hoy me sentí... Estoy agradecido por... Mañana quiero... Mi pequeño hábito de hoy fue..."], m_6: ["Worship", "Paz en el presente", "El pasado no se cambia. El futuro no existe aún. Solo tienes este momento. Entrégalo con paz."] },
  },
};

export type Dict = typeof es;

const en: Dict = {
  nav: { hoy: "Today", entrenar: "Train", comidas: "Meals", mente: "Mind", progreso: "Progress", menus: "Menus", chat: "Chat", soporte: "Support", planes: "Plans", perfil: "Profile", micoach: "My coach", salir: "Log out", panelCoach: "Coach panel", admin: "Admin" },
  common: { gratis: "Free", premium: "Premium", desde: "From", desdePlan: "Available from the", desbloquear: "Unlock", verPlanes: "See plans", guardar: "Save", enviar: "Send", agregar: "Add", empezarGratis: "Start free", crearCuenta: "Create account", iniciarSesion: "Log in", entrar: "Enter", volver: "← Back", min: "min", ejercicios: "exercises", mes: "/mo", disclaimer: "Educational content. Everyone practices it at their own responsibility; consult a health professional.", issa: "ISSA-certified coach · CPT · Nutrition · Strength & Conditioning", tagline: "Small habits, big results" },
  home: { pill: "Gym · Nutrition · Peace of mind", h1a: "Energy to move.", h1b: "Calm to stay.", text: "Train with a timer and video guide, log your meals, and care for your mind with reflection and worship. With Maleja, ISSA-certified coach, in your language.", go: "GO · Start free", miembros: "members", anos: "years", transf: "transformations", energia: "Energy", entrenar: "Train", entrenarText: "Functional, calisthenics, HIIT. Interval timer, guided sets and rests, video demo.", verRutinas: "See routines", balance: "Balance", comerBien: "Eat well and be at peace", comerBienText: "Goal-based menus, meal log, pilates, yoga, daily reflection and worship.", explorar: "Explore", tuCoach: "Your coach", coachBio: "ISSA-certified coach (CPT, Nutrition Coach, Strength & Conditioning). She changed her life with small habits; today she guides hundreds of women in three languages. 1:1 chat and a plan made for you from the Pro plan.", planes: "Plans", planesSub: "Start free. Upgrade whenever you want more.", free: ["2 routines with timer", "1 menu with recipes", "Reflection + worship", "Meal log", "AI assistant (5/day)", "Support"], crearGratis: "Create free account", elegir: "Choose", masElegido: "Most chosen", footer: "Educational content. Everyone practices it at their own responsibility; consult a health professional before starting a program." },
  auth: { email: "Email", password: "Password", name: "Your name", namePh: "What the app should call you", goal: "Your goal", coachQ: "Are you a coach? Enter your code", coachCode: "Coach code", coachHint: "Only for coaches invited by Small Habits. Members leave it empty.", entrar: "Log in", crear: "Create my account", wait: "One moment…", haveAccount: "Already have an account?", firstTime: "First time?", crearGratis: "Create your free account", signupPill: "Create your free account", signupSub: "No card needed. Free stays free: 2 routines, 1 menu, daily reflection and your meal log.", signupFine: "By creating your account you accept that the content is educational and you practice it at your own responsibility.", hub: "Wellness hub · by Maleja", quote: "Wellness from the inside out." },
  goals: { Tonificar: "Tone up", "Perder peso": "Lose weight", "Ganar fuerza": "Gain strength", Resistencia: "Endurance", Flexibilidad: "Flexibility", "Salud integral": "Overall health" },
  dash: { hola: "Hi", objetivo: "goal", quote: "One small habit today. One more tomorrow.", hoyToca: "Today", asignadoPor: "Assigned by", empiezaSuave: "Start gently. What matters is starting.", calorias: "Calories", de: "of", peso: "Weight", kg: "kg", addProfile: "add it in your profile", entrenos: "Workouts", estaSemana: "this week", diasActivos: "Active days", ult30: "last 30 days", nutricion: "Nutrition", sinComidas: "No meals logged yet today", quedan: "{n} kcal left", registrar: "Log a meal", verMenu: "See menu", pazMental: "Peace of mind", reflexionHoy: "Today's reflection · 5 min", quoteMente: "Breathe. Be grateful for your body, which moved today.", unread: "You have {n} unread message(s).", welcome: "Welcome, {n}. Tell me how you feel today and we'll plan your week.", eligeCoach: "Choose your coach", nuevo: "{n} new" },
  routines: { title: "Train", kicker: "2 free routines · the rest from Basic", demo: "Avatar demo", ejercicios: "Exercises", series: "Sets", reps: "Reps", descanso: "Rest", musculos: "Muscles", warn: "Perform the exercises at your own responsibility. Stop if you feel any pain.", trabajo: "Work", descansoT: "Rest", pausa: "Pause", reiniciar: "Reset", completada: "Session complete", completadaText: "Energy rests. Log how you felt in Progress.", repetir: "Repeat" },
  nutrition: { title: "Menus & recipes", kicker: "1 free menu · the rest from Basic", avatar: "Avatar explains", planDia: "Daily plan", recetas: "Recipes", marcas: "Brands recommended for clean ingredients:", marcasText: "oats with no added sugar, protein without artificial sweeteners, extra virgin olive oil, pasture-raised eggs. Always read the label.", menu: "Menu", kcalDia: "kcal/day" },
  mind: { title: "Peace of mind", kicker: "Reflection and worship free · meditation and journal from Basic", avatar: "Avatar guide", completar: "Complete session", guardar: "Save", respiracion: "4-7-8 breathing", banner: "Breathe. Today counts too.", journalPh: "Write here...", inhala: "Inhale", sosten: "Hold", exhala: "Exhale" },
  food: { title: "Meals", kicker: "Manual log free · photo with AI from Basic", fotoIA: "Photo → AI", tocaFoto: "Tap to take a photo of your plate", desdeBasico: "From the Basic plan", probar: "Try with a sample photo", analizando: "Analyzing your meal…", manual: "Manual log", quecomiste: "What did you eat?", calorias: "Approx. calories", guardando: "Saving…", hoy: "Today", proteina: "Protein", carbos: "Carbs", grasas: "Fat", sinComidas: "No meals yet today. Log the first one above.", hist30: "30-day history", ult30: "Last 30 days", histText: "Average, protein and weekly trend appear here from your second day of logging.", err: "Couldn't save. Check your connection and try again." },
  progress: { title: "Progress", kicker: "8 weeks with you", banner: "Every day adds up.", racha: "Streak", peso: "Weight", entrenos: "Workouts", totales: "total", dias: "days · best 19", pesoSem: "Weight · 8 weeks", kcalSem: "Calories · this week", kcalFeature: "Weekly calories", reloj: "Watch connected", relojFeature: "Apple Watch and Garmin", sync: "synced", pasos: "Steps", bpm: "Resting BPM", kcalAct: "Active kcal", sueno: "Sleep", via: "Via Apple HealthKit and Garmin Connect API. Syncs every 15 minutes." },
  chat: { title: "Chat", kicker: "AI assistant free · your coach from Pro", ia: "AI assistant", ilimitado: "Unlimited", porDia: "5 / day", iaFine: "General, educational information. Not medical advice.", feature: "Direct chat with", coachFine: "Your coach usually replies within 24 h. Messages are saved.", limite: "Daily limit — upgrade for unlimited", placeholder: "Type your question…", writeTo: "Write to", desdePro: "Available from the Pro plan", noCoach: "There's no coach on the platform yet. As soon as one joins, your message reaches her.", firstMsg: "Write the first message to", msgsHoy: "messages today", hello: "Hi {n}. I'm your assistant. What do you need today: calories, a routine, a menu or a moment of peace?" },
  upgrade: { title: "Plans", kicker: "Free stays free. Paid access activates only when Stripe confirms.", masElegido: "Most chosen", elite: "Guided transformation", tuPlan: "Your plan", suscribir: "Subscribe with Stripe", pendiente: "Payment link pending", demo: "Demo mode", demoText: "Switch plan without paying to show how the app looks at each level. Disabled in production.", verComo: "View as" },
  coaches: { title: "Choose your coach", kicker: "Change anytime · your history is kept", intro: "Every coach has her style. Choose the person you trust: she'll assign your routine and menu and be the one you chat with.", tuCoach: "Your coach", noBio: "This coach hasn't written her intro yet.", miembros: "member(s)", elegirA: "Choose", none: "No coaches registered yet.", defaultSpec: "Small Habits coach" },
  profile: { title: "My profile", cuenta: "Account created", plan: "plan", nombre: "Name", objetivo: "Goal", pesoKg: "Weight (kg)", alturaCm: "Height (cm)", note: "Each time you save a new weight it's added to your progress history.", guardar: "Save changes", guardando: "Saving…", cerrar: "Log out" },
  tickets: { title: "Support", kicker: "Free for everyone · priority on Elite", nuevo: "New ticket", prio: "Priority · 24h", asunto: "Subject", cuenta: "Tell us what's going on…", enviar: "Send ticket", mis: "My tickets", cats: ["Training", "Nutrition", "Billing", "Technical", "Other"] },
  wearables: { title: "My watch", kicker: "Sync steps, sleep and workouts · from Pro", feature: "Connect your watch", connected: "Connected", notConnected: "Not connected", connectGoogle: "Connect with Google Health", googleText: "Fitbit, Pixel Watch and Android watches (Wear OS, Samsung) through the Google Health app.", garminText: "Access request sent to Garmin. Activates once approved.", appleText: "Apple only allows reading Apple Watch data from an app installed on the iPhone. Coming with the App Store version.", soon: "Coming soon", lastSync: "Last sync", syncNow: "Sync now", disconnect: "Disconnect", connectedMsg: "Watch connected. Your data starts showing here and in Progress.", noDataYet: "No data yet: wear the watch for a few hours and sync again.", errorMsg: "Couldn't connect. Please try again.", todayData: "Today", history: "Last 14 days", day: "Day", privacy: "Only daily summaries are stored (steps, resting heart rate, active calories, sleep, workouts). Disconnect anytime and they are deleted." },
  plans: {
    basico: { tagline: "Train and eat well", features: ["All routines (functional, calisthenics, pilates, yoga, stretching)", "All menus and recipes", "Meal log with photo (10/day)", "Full meditations and worship", "Full progress with charts"] },
    pro: { tagline: "With your coach", features: ["Everything in Basic", "1:1 chat with your coach", "Unlimited AI assistant", "Unlimited meal log", "Weekly plan assigned by your coach"] },
    elite: { tagline: "Guided transformation", features: ["Everything in Pro", "Training and nutrition plan made by your coach for you", "Monthly 1:1 video call", "Unlimited 1:1 chat", "Priority support"] },
  },
  content: {
    routines: { routine_1: ["Calisthenics for beginners", "Basic bodyweight movements. Perfect to get started."], routine_2: ["Functional HIIT 20 min", "High-intensity intervals. Maximum burn in little time."], routine_3: ["Pilates for flexibility", "Gentle session focused on lengthening and control."], routine_4: ["Yoga Vinyasa Flow", "Continuous sequence of poses linked with breath."], routine_5: ["Post-workout stretching", "Lengthening for recovery after training."] },
    menus: { menu_1: "Toning", menu_2: "Fat loss", menu_3: "Muscle gain", menu_4: "Vegetarian balance" },
    sessions: { m_1: ["Reflection", "Small habits, big changes", "Which small habit did you keep today? Write it down. Size doesn't matter: repetition does. Tomorrow, do it once more."], m_2: ["Worship", "Gratitude and purpose", "Breathe. Give thanks for your body, which moved today. Give thanks for your mind, which chose to care for itself. Ask for strength for tomorrow."], m_3: ["Meditation", "Before training: focus", "Close your eyes. Picture your whole session. Every rep with intention. You are capable."], m_4: ["Meditation", "Post-workout recovery", "Your body worked. Breathe slowly. Feel tiredness turn into satisfaction. Rest."], m_5: ["Journal", "Evening journal", "Today I felt... I'm grateful for... Tomorrow I want... My small habit today was..."], m_6: ["Worship", "Peace in the present", "The past can't be changed. The future doesn't exist yet. You only have this moment. Offer it with peace."] },
  },
};

const pt: Dict = {
  nav: { hoy: "Hoje", entrenar: "Treinar", comidas: "Refeições", mente: "Mente", progreso: "Progresso", menus: "Cardápios", chat: "Chat", soporte: "Suporte", planes: "Planos", perfil: "Perfil", micoach: "Minha coach", salir: "Sair", panelCoach: "Painel coach", admin: "Admin" },
  common: { gratis: "Grátis", premium: "Premium", desde: "A partir de", desdePlan: "Disponível a partir do plano", desbloquear: "Desbloquear", verPlanes: "Ver planos", guardar: "Salvar", enviar: "Enviar", agregar: "Adicionar", empezarGratis: "Começar grátis", crearCuenta: "Criar conta", iniciarSesion: "Entrar", entrar: "Entrar", volver: "← Voltar", min: "min", ejercicios: "exercícios", mes: "/mês", disclaimer: "Conteúdo educativo. Cada pessoa pratica sob sua própria responsabilidade; consulte um profissional de saúde.", issa: "Coach certificada ISSA · CPT · Nutrição · Força e condicionamento", tagline: "Pequenos hábitos, grandes resultados" },
  home: { pill: "Academia · Nutrição · Paz mental", h1a: "Energia para se mover.", h1b: "Calma para ficar.", text: "Treine com cronômetro e guia em vídeo, registre suas refeições e cuide da mente com reflexão e worship. Com Maleja, coach certificada ISSA, no seu idioma.", go: "GO · Começar grátis", miembros: "membros", anos: "anos", transf: "transformações", energia: "Energia", entrenar: "Treinar", entrenarText: "Funcional, calistenia, HIIT. Cronômetro por intervalos, séries e descansos guiados, demo em vídeo.", verRutinas: "Ver treinos", balance: "Equilíbrio", comerBien: "Comer bem e estar em paz", comerBienText: "Cardápios por objetivo, registro de refeições, pilates, yoga, reflexão diária e worship.", explorar: "Explorar", tuCoach: "Sua coach", coachBio: "Coach certificada ISSA (CPT, Nutrition Coach, Strength & Conditioning). Mudou a vida com pequenos hábitos; hoje acompanha centenas de mulheres em três idiomas. Chat 1:1 e plano sob medida a partir do plano Pro.", planes: "Planos", planesSub: "Comece grátis. Suba quando quiser mais.", free: ["2 treinos com cronômetro", "1 cardápio com receitas", "Reflexão + worship", "Registro de refeições", "Assistente IA (5/dia)", "Suporte"], crearGratis: "Criar conta grátis", elegir: "Escolher", masElegido: "Mais escolhido", footer: "Conteúdo educativo. Cada pessoa pratica sob sua própria responsabilidade; consulte um profissional de saúde antes de iniciar um programa." },
  auth: { email: "Email", password: "Senha", name: "Seu nome", namePh: "Como o app deve te chamar", goal: "Seu objetivo", coachQ: "Você é coach? Digite seu código", coachCode: "Código de coach", coachHint: "Só para coaches convidadas pela Small Habits. Membros deixam em branco.", entrar: "Entrar", crear: "Criar minha conta", wait: "Um momento…", haveAccount: "Já tem conta?", firstTime: "Primeira vez?", crearGratis: "Crie sua conta grátis", signupPill: "Crie sua conta grátis", signupSub: "Sem cartão. O grátis continua grátis: 2 treinos, 1 cardápio, reflexão diária e seu registro de refeições.", signupFine: "Ao criar sua conta você aceita que o conteúdo é educativo e o pratica sob sua responsabilidade.", hub: "Hub wellness · by Maleja", quote: "Wellness from the inside out." },
  goals: { Tonificar: "Tonificar", "Perder peso": "Perder peso", "Ganar fuerza": "Ganhar força", Resistencia: "Resistência", Flexibilidad: "Flexibilidade", "Salud integral": "Saúde integral" },
  dash: { hola: "Olá", objetivo: "objetivo", quote: "Um pequeno hábito hoje. Mais um amanhã.", hoyToca: "Hoje é dia de", asignadoPor: "Atribuído por", empiezaSuave: "Comece leve. O importante é começar.", calorias: "Calorias", de: "de", peso: "Peso", kg: "kg", addProfile: "adicione no seu perfil", entrenos: "Treinos", estaSemana: "esta semana", diasActivos: "Dias ativos", ult30: "últimos 30 dias", nutricion: "Nutrição", sinComidas: "Nenhuma refeição registrada hoje", quedan: "Faltam {n} kcal", registrar: "Registrar refeição", verMenu: "Ver cardápio", pazMental: "Paz mental", reflexionHoy: "Reflexão de hoje · 5 min", quoteMente: "Respire. Agradeça pelo seu corpo, que hoje se moveu.", unread: "Você tem {n} mensagem(ns) não lida(s).", welcome: "Bem-vinda, {n}. Me conte como você se sente hoje e montamos sua semana.", eligeCoach: "Escolha sua coach", nuevo: "{n} nova(s)" },
  routines: { title: "Treinar", kicker: "2 treinos grátis · o resto a partir do Básico", demo: "Demo avatar", ejercicios: "Exercícios", series: "Séries", reps: "Reps", descanso: "Descanso", musculos: "Músculos", warn: "Faça os exercícios sob sua responsabilidade. Pare diante de qualquer dor.", trabajo: "Trabalho", descansoT: "Descanso", pausa: "Pausar", reiniciar: "Reiniciar", completada: "Sessão concluída", completadaText: "A energia descansa. Registre como se sentiu em Progresso.", repetir: "Repetir" },
  nutrition: { title: "Cardápios e receitas", kicker: "1 cardápio grátis · o resto a partir do Básico", avatar: "Avatar explica", planDia: "Plano do dia", recetas: "Receitas", marcas: "Marcas recomendadas por ingredientes limpos:", marcasText: "aveia sem açúcar, proteína sem adoçantes artificiais, azeite extra virgem, ovos caipiras. Leia sempre o rótulo.", menu: "Cardápio", kcalDia: "kcal/dia" },
  mind: { title: "Paz mental", kicker: "Reflexão e worship grátis · meditação e diário a partir do Básico", avatar: "Avatar guia", completar: "Concluir sessão", guardar: "Salvar", respiracion: "Respiração 4-7-8", banner: "Respire. Hoje também conta.", journalPh: "Escreva aqui...", inhala: "Inspire", sosten: "Segure", exhala: "Expire" },
  food: { title: "Refeições", kicker: "Registro manual grátis · foto com IA a partir do Básico", fotoIA: "Foto → IA", tocaFoto: "Toque para fotografar seu prato", desdeBasico: "A partir do plano Básico", probar: "Testar com foto de exemplo", analizando: "Analisando sua refeição…", manual: "Registro manual", quecomiste: "O que você comeu?", calorias: "Calorias aprox.", guardando: "Salvando…", hoy: "Hoje", proteina: "Proteína", carbos: "Carbos", grasas: "Gorduras", sinComidas: "Nenhuma refeição hoje ainda. Registre a primeira acima.", hist30: "Histórico de 30 dias", ult30: "Últimos 30 dias", histText: "Média, proteína e tendência semanal aparecem aqui a partir do segundo dia de registro.", err: "Não foi possível salvar. Verifique sua conexão e tente de novo." },
  progress: { title: "Progresso", kicker: "8 semanas com você", banner: "Cada dia soma.", racha: "Sequência", peso: "Peso", entrenos: "Treinos", totales: "no total", dias: "dias · melhor 19", pesoSem: "Peso · 8 semanas", kcalSem: "Calorias · esta semana", kcalFeature: "Calorias semanais", reloj: "Relógio conectado", relojFeature: "Apple Watch e Garmin", sync: "sincronizado", pasos: "Passos", bpm: "BPM em repouso", kcalAct: "Kcal ativas", sueno: "Sono", via: "Via Apple HealthKit e Garmin Connect API. Sincroniza a cada 15 minutos." },
  chat: { title: "Chat", kicker: "Assistente IA grátis · sua coach a partir do Pro", ia: "Assistente IA", ilimitado: "Ilimitado", porDia: "5 / dia", iaFine: "Informação geral e educativa. Não substitui orientação médica.", feature: "Chat direto com", coachFine: "Sua coach costuma responder em menos de 24 h. As mensagens ficam salvas.", limite: "Limite diário — suba de plano para ilimitado", placeholder: "Escreva sua pergunta…", writeTo: "Escreva para", desdePro: "Disponível a partir do plano Pro", noCoach: "Ainda não há coach na plataforma. Assim que entrar, sua mensagem chega a ela.", firstMsg: "Escreva a primeira mensagem para", msgsHoy: "mensagens hoje", hello: "Olá {n}. Sou sua assistente. O que você precisa hoje: calorias, treino, cardápio ou um momento de paz?" },
  upgrade: { title: "Planos", kicker: "O grátis continua grátis. O pago ativa só quando o Stripe confirma.", masElegido: "Mais escolhido", elite: "Transformação guiada", tuPlan: "Seu plano", suscribir: "Assinar com Stripe", pendiente: "Link de pagamento pendente", demo: "Modo demonstração", demoText: "Troque o plano sem pagar para mostrar como o app fica em cada nível. Desativado em produção.", verComo: "Ver como" },
  coaches: { title: "Escolha sua coach", kicker: "Mude quando quiser · seu histórico é mantido", intro: "Cada coach tem seu estilo. Escolha a pessoa que te inspira confiança: ela vai atribuir seu treino e cardápio e será com quem você conversa no chat.", tuCoach: "Sua coach", noBio: "Esta coach ainda não escreveu sua apresentação.", miembros: "membro(s)", elegirA: "Escolher", none: "Ainda não há coaches cadastradas.", defaultSpec: "Coach Small Habits" },
  profile: { title: "Meu perfil", cuenta: "Conta criada em", plan: "plano", nombre: "Nome", objetivo: "Objetivo", pesoKg: "Peso (kg)", alturaCm: "Altura (cm)", note: "Cada vez que você salva um peso novo, ele entra no seu histórico de progresso.", guardar: "Salvar alterações", guardando: "Salvando…", cerrar: "Sair" },
  tickets: { title: "Suporte", kicker: "Grátis para todos · prioridade no Elite", nuevo: "Novo ticket", prio: "Prioritário · 24h", asunto: "Assunto", cuenta: "Conte o que está acontecendo…", enviar: "Enviar ticket", mis: "Meus tickets", cats: ["Treino", "Nutrição", "Pagamentos", "Técnico", "Outro"] },
  wearables: { title: "Meu relógio", kicker: "Sincronize passos, sono e treinos · a partir do Pro", feature: "Conectar seu relógio", connected: "Conectado", notConnected: "Não conectado", connectGoogle: "Conectar com Google Health", googleText: "Fitbit, Pixel Watch e relógios Android (Wear OS, Samsung) pelo app Google Health.", garminText: "Pedido de acesso enviado à Garmin. Ativa assim que for aprovado.", appleText: "A Apple só permite ler dados do Apple Watch por um app instalado no iPhone. Chega com a versão para App Store.", soon: "Em breve", lastSync: "Última sincronização", syncNow: "Sincronizar agora", disconnect: "Desconectar", connectedMsg: "Relógio conectado. Seus dados começam a aparecer aqui e em Progresso.", noDataYet: "Ainda sem dados: use o relógio por algumas horas e sincronize de novo.", errorMsg: "Não foi possível conectar. Tente de novo.", todayData: "Hoje", history: "Últimos 14 dias", day: "Dia", privacy: "Só guardamos resumos diários (passos, batimentos em repouso, calorias ativas, sono, treinos). Desconecte quando quiser e eles são apagados." },
  plans: {
    basico: { tagline: "Treine e coma bem", features: ["Todos os treinos (funcional, calistenia, pilates, yoga, alongamento)", "Todos os cardápios e receitas", "Registro de refeições com foto (10/dia)", "Meditações e worship completos", "Progresso completo com gráficos"] },
    pro: { tagline: "Com sua coach", features: ["Tudo do Básico", "Chat 1:1 com sua coach", "Assistente IA ilimitado", "Registro de refeições ilimitado", "Plano da semana atribuído pela sua coach"] },
    elite: { tagline: "Transformação guiada", features: ["Tudo do Pro", "Plano de treino e nutrição feito pela sua coach para você", "Videochamada mensal 1:1", "Chat 1:1 ilimitado", "Suporte prioritário"] },
  },
  content: {
    routines: { routine_1: ["Calistenia para iniciantes", "Movimentos básicos com peso corporal. Perfeito para começar."], routine_2: ["HIIT funcional 20 min", "Alta intensidade por intervalos. Queima máxima em pouco tempo."], routine_3: ["Pilates para flexibilidade", "Sessão suave focada em alongamento e controle."], routine_4: ["Yoga Vinyasa Flow", "Sequência contínua de posturas ligadas à respiração."], routine_5: ["Alongamento pós-treino", "Alongamento para recuperação depois do treino."] },
    menus: { menu_1: "Tonificação", menu_2: "Perda de gordura", menu_3: "Ganho muscular", menu_4: "Vegetariano equilibrado" },
    sessions: { m_1: ["Reflexão", "Pequenos hábitos, grandes mudanças", "Qual pequeno hábito você cumpriu hoje? Anote. Não importa o tamanho: importa a repetição. Amanhã, repita mais uma vez."], m_2: ["Worship", "Gratidão e propósito", "Respire. Agradeça pelo seu corpo, que hoje se moveu. Agradeça pela sua mente, que hoje escolheu se cuidar. Peça força para amanhã."], m_3: ["Meditação", "Antes do treino: foco", "Feche os olhos. Visualize sua sessão completa. Cada repetição com intenção. Você é capaz."], m_4: ["Meditação", "Recuperação pós-treino", "Seu corpo trabalhou. Respire devagar. Sinta o cansaço virar satisfação. Descanse."], m_5: ["Diário", "Diário da noite", "Hoje me senti... Sou grata por... Amanhã quero... Meu pequeno hábito de hoje foi..."], m_6: ["Worship", "Paz no presente", "O passado não muda. O futuro ainda não existe. Você só tem este momento. Entregue-o com paz."] },
  },
};

const dicts: Record<Lang, Dict> = { es, en, pt };

export async function getLang(): Promise<Lang> {
  const c = (await cookies()).get("sh_lang")?.value as Lang | undefined;
  if (c && LANGS.includes(c)) return c;
  const al = ((await headers()).get("accept-language") || "").toLowerCase();
  if (al.startsWith("en")) return "en";
  if (al.startsWith("pt")) return "pt";
  return "es";
}

export async function tr(): Promise<{ lang: Lang; L: Dict }> {
  const lang = await getLang();
  return { lang, L: dicts[lang] };
}

export const fill = (s: string, n: string | number) => s.replace("{n}", String(n));
export const locale = (l: Lang) => (l === "en" ? "en-US" : l === "pt" ? "pt-BR" : "es");
